#ifndef HZCOMPONENT_GLOBAL_H
#define HZCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HZCOMPONENT_LIBRARY)
#  define HZCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HZCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HZCOMPONENT_GLOBAL_H
