#ifndef HZINFOCENTER_GLOBAL_H
#define HZINFOCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HZINFOCENTER_LIBRARY)
#  define HZINFOCENTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HZINFOCENTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HZINFOCENTER_GLOBAL_H
